version: '3'
services: 
  xrayr: 
    image: monlor/xrayr:main
    container_name: xrayr
    environment:
      - API_HOST=
      - API_KEY=
      - NODE_ID=
      #  V2ray, Shadowsocks, Trojan
      - NODE_TYPE=
      - DOMAIN=hk01.example.com
      - EMAIL=admin@example.com
    restart: unless-stopped
    network_mode: host
