version: '3'
services: 
  xrayr: 
    image: monlor/xrayr:main
    container_name: xrayr
    environment:
      - API_HOST=
      - API_KEY=
      - NODE_ID=1
      #  V2ray, Shadowsocks, Trojan
      - NODE_TYPE=Trojan
      # for cert
      - DOMAIN=hk01.example.com
      - EMAIL=admin@example.com
      # default http
      # file: /etc/XrayR/cert/node.crt /etc/XrayR/cert/node.key
      - CERT_MODE=http
      # CERT_MODE=dns required
      - CLOUDFLARE_API_KEY=xxx
      - ENABLE_FALLBACK=true
      - ENABLE_DNS=true
      # 本地节点限速，优先级高于面板，单位Mbps
      # SPEED_LIMIT=10
      # 流媒体解锁dns
      - MEDIA_DNS_SERVER=1.2.3.4
      # device limit
      # - DEVICE_LIMIT=true
      # - REDIS_ADDR=127.0.0.1:6379
      # - REDIS_PASSWORD=123456
      # chatgpt outbound, ChatGPT(default) Warp IPv4_out IPv6_out
      # - CHATGPT_OUT=Warp
      # 住宅ip出口代理
      # - RESIDENTIAL_PROXY=true
      # - RESIDENTIAL_PROXY_USER=xxx
      # - RESIDENTIAL_PROXY_PASS=xxx
      # - RESIDENTIAL_PROXY_PORT=22225
      # - RESIDENTIAL_PROXY_SERVER=x.x.x.x
    volumes:
      - certs:/etc/XrayR/cert
    restart: unless-stopped
    network_mode: host

volumes:
  certs: