version: '3'
services: 
  xrayr: 
    image: monlor/xrayr:main
    container_name: xrayr
    environment:
      - API_HOST=
      - API_KEY=
      - NODE_ID=1
      #  V2ray, Shadowsocks, Trojan
      - NODE_TYPE=Trojan
      # for cert
      - DOMAIN=hk01.example.com
      - EMAIL=admin@example.com
      # default http
      # file: /etc/XrayR/cert/node.crt /etc/XrayR/cert/node.key
      - CERT_MODE=http
      # CERT_MODE=dns required
      - CLOUDFLARE_API_KEY=xxx
      - ENABLE_FALLBACK=true
      # device limit
      # - DEVICE_LIMIT=true
      # - REDIS_ADDR=127.0.0.1:6379
      # - REDIS_PASSWORD=123456
      # media unlock outbound, Warp(default) IPv4_out IPv6_out
      # - MEDIA_OUT=IPv6_out
      # chatgpt outbountd, ChatGPT(default) Warp IPv4_out IPv6_out
      # - CHATGPT_OUT=Warp
    volumes:
      - certs:/etc/XrayR/cert
    restart: unless-stopped
    network_mode: host

volumes:
  certs: